vim.pack.add({ "https://github.com/neogitorg/neogit" })

local neogit = require("neogit")
local map = vim.keymap.set

neogit.setup({
	integrations = { diffview = true },
	mappings = {
		commit_editor = {
			["q"] = "Close",
			["<c-c><c-c>"] = "Submit",
			["<c-c><c-k>"] = "Abort",
			["<m-p>"] = "PrevMessage",
			["<m-n>"] = "NextMessage",
			["<m-r>"] = "ResetMessage",
		},
		commit_editor_I = {
			["<c-c><c-c>"] = "Submit",
			["<c-c><c-k>"] = "Abort",
		},
		rebase_editor = {
			["p"] = "Pick",
			["r"] = "Reword",
			["e"] = "Edit",
			["s"] = "Squash",
			["f"] = "Fixup",
			["x"] = "Execute",
			["d"] = "Drop",
			["b"] = "Break",
			["q"] = "Close",
			["<cr>"] = "OpenCommit",
			["gk"] = "MoveUp",
			["gj"] = "MoveDown",
			["<c-k>"] = "MoveUp",
			["<c-j>"] = "MoveDown",
			["<c-c><c-c>"] = "Submit",
			["<c-c><c-k>"] = "Abort",
			["[c"] = "OpenOrScrollUp",
			["]c"] = "OpenOrScrollDown",
		},
		rebase_editor_I = {
			["<c-c><c-c>"] = "Submit",
			["<c-c><c-k>"] = "Abort",
		},
		finder = {
			["<cr>"] = "Select",
			["<c-c>"] = "Close",
			["<esc>"] = "Close",
			["<c-n>"] = "Next",
			["<c-p>"] = "Previous",
			["<down>"] = "Next",
			["<up>"] = "Previous",
			["<tab>"] = "InsertCompletion",
			["<c-y>"] = "CopySelection",
			["<space>"] = "MultiselectToggleNext",
			["<s-space>"] = "MultiselectTogglePrevious",
			["<c-j>"] = "NOP",
			["<ScrollWheelDown>"] = "ScrollWheelDown",
			["<ScrollWheelUp>"] = "ScrollWheelUp",
			["<ScrollWheelLeft>"] = "NOP",
			["<ScrollWheelRight>"] = "NOP",
			["<LeftMouse>"] = "MouseClick",
			["<2-LeftMouse>"] = "NOP",
		},
		-- Setting any of these to `false` will disable the mapping.
		popup = {
			["?"] = "HelpPopup",
			["x"] = "HelpPopup",
			["A"] = false,
			["C"] = "CherryPickPopup",
			["d"] = false,
			["W"] = "DiffPopup",
			["M"] = "RemotePopup",
			["P"] = "PushPopup",
			["X"] = false,
			["D"] = "ResetPopup",
			["Z"] = false,
			["s"] = "StashPopup",
			["S"] = "StashPopup",
			["i"] = "IgnorePopup",
			["t"] = "RevertPopup",
			["T"] = "TagPopup",
			["b"] = "BranchPopup",
			["B"] = "BisectPopup",
			["w"] = "WorktreePopup",
			["c"] = "CommitPopup",
			["f"] = "FetchPopup",
			["l"] = "LogPopup",
			["m"] = "MergePopup",
			["p"] = "PullPopup",
			["r"] = "RebasePopup",
			["v"] = false,
		},
		status = {
			["j"] = "MoveDown",
			["k"] = "MoveUp",
			["o"] = false,
			["q"] = "Close",
			["I"] = "InitRepo",
			["1"] = "Depth1",
			["2"] = "Depth2",
			["3"] = "Depth3",
			["4"] = "Depth4",
			["Q"] = "Command",
			["<tab>"] = "Toggle",
			["za"] = "Toggle",
			["zo"] = "OpenFold",
			["x"] = false,
			["d"] = "Discard",
			["<space>"] = "Stage",
			["s"] = false,
			["S"] = false,
			["a"] = "StageAll",
			["<c-s>"] = false,
			["u"] = "Unstage",
			["K"] = "Untrack",
			["U"] = "UnstageStaged",
			["y"] = "ShowRefs",
			["$"] = "CommandHistory",
			["Y"] = "YankSelected",
			["gp"] = "GoToParentRepo",
			["R"] = "RefreshBuffer",
			["<c-r>"] = false,
			["<cr>"] = "GoToFile",
			["<s-cr>"] = "PeekFile",
			["<c-v>"] = "VSplitOpen",
			["<c-x>"] = "SplitOpen",
			["<c-t>"] = "TabOpen",
			["{"] = "GoToPreviousHunkHeader",
			["}"] = "GoToNextHunkHeader",
			["[c"] = "OpenOrScrollUp",
			["]c"] = "OpenOrScrollDown",
			["<c-k>"] = "PeekUp",
			["<c-j>"] = "PeekDown",
			["<c-n>"] = "NextSection",
			["<c-p>"] = "PreviousSection",
		},
	},
})

map("n", "<D-BS>", function()
	neogit.open({ kind = "tab" })
end, { desc = "Neogit open" })
